### ISSUE TITLE
Better errors

### ISSUE THREAD

**Issue by tvararu** [dtinth/prettier-standard-formatter#8]
If a project uses https://github.com/babel/babel-eslint, but you don't have it installed globally, you can get an error that simply reads `'Expected a string back from standard'`.

This is because in https://github.com/dtinth/prettier-standard-formatter/blob/d2fef5bf61d42b4ac09c9f2541bbb3269b676796/index.js#L17, `output` is undefined. `result.results[0].messages` does contain a useful object:

```js
   [ { ruleId: null,
       fatal: true,
       severity: 2,
       source: null,
       message: 'Cannot find module \'babel-eslint\'',
       line: 0,
       column: 0 } ],
```

I think exposing this in the error output would be useful.

**Comment by brandonb927** [comment]
Not sure if this is related but I just ran into this issue with blank `tests.js` files on a new project I'm working on using this plugin. I'm seeing `Expected a string back from standard` when it attempts to lint js files with no content.

**Comment by sebinsua** [comment]
> Not sure if this is related but I just ran into this issue with blank tests.js files on a new project I'm working on using this plugin.

I just had this exact issue. Does anybody else think it would be better it the behavior in this case was to warn and not error?
